import type { Metadata } from 'next'
//import Navbar from '../app/Components/navbar'
import { Inter } from 'next/font/google'
import './globals.css'
import dynamic from 'next/dynamic';

const DynamicNavbar = dynamic(() => import('../app/Components/navbar'), { ssr: false });
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <DynamicNavbar/>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
