/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/token": {
    post: operations["login_for_access_token_token_post"];
  };
  "/employees/": {
    /**
     * Retrieve a list of employees based on the provided search criteria. If no search criteria is provided, return all employees.
     *
     * Permissions:
     * - Admins and owners can view all employees.
     * - Team leaders can only view their own team members.
     * - Other employees can only view themselves.
     */
    get: operations["get_employees_employees__get"];
    /** Create a new employee. */
    post: operations["create_employee_employees__post"];
  };
  "/employees/{employee_id}": {
    /**
     * Retrieve information about a specific employee by `id`.
     *
     * Permissions:
     * - Admins and owners can view all employees.
     * - Team leaders can only view their own team members.
     * - Other employees can only view themselves.
     */
    get: operations["get_employee_employees__employee_id__get"];
    /**
     * Update information about a specific employee by `id`.
     *
     * Permissions:
     * - Admins and owners can update all employees.
     */
    put: operations["update_employee_employees__employee_id__put"];
    /** Delete a specific employee by `id`. */
    delete: operations["delete_employee_employees__employee_id__delete"];
  };
  "/employees/email/{email}": {
    /**
     * Retrieve information about a specific employee by `bussines_email`.
     *
     * Permissions:
     * - Admins and owners can view all employees.
     * - Team leaders can only view their own team members.
     * - Other employees can only view themselves.
     */
    get: operations["get_employee_by_email_employees_email__email__get"];
  };
  "/employees/register": {
    /**
     * Register a new employee.
     *
     * Permissions:
     * - Only unregistered employees can register.
     */
    put: operations["register_employee_employees_register_put"];
  };
  "/accounts/sales": {
    get: operations["get_sales_accounts_accounts_sales_get"];
    put: operations["update_sales_account_accounts_sales_put"];
    post: operations["create_sales_account_accounts_sales_post"];
    delete: operations["delete_sales_account_accounts_sales_delete"];
  };
  "/leads/rotate": {
    post: operations["rotate_lead_leads_rotate_post"];
  };
  "/leads/": {
    get: operations["get_leads_leads__get"];
    put: operations["update_lead_leads__put"];
    post: operations["create_lead_leads__post"];
    delete: operations["delete_lead_leads__delete"];
  };
  "/accounts/company": {
    get: operations["get_company_accounts_accounts_company_get"];
    put: operations["update_company_account_accounts_company_put"];
    delete: operations["delete_company_account_accounts_company_delete"];
  };
  "/teams/": {
    get: operations["get_teams_teams__get"];
  };
  "/actions/": {
    get: operations["get_actions_actions__get"];
  };
  "/accounts/sales/calls": {
    get: operations["get_sales_calls_accounts_sales_calls_get"];
    put: operations["update_sales_call_accounts_sales_calls_put"];
    post: operations["create_sales_call_accounts_sales_calls_post"];
    delete: operations["delete_sales_call_accounts_sales_calls_delete"];
  };
  "/accounts/company/calls": {
    get: operations["get_company_calls_accounts_company_calls_get"];
    put: operations["update_company_call_accounts_company_calls_put"];
    post: operations["create_company_call_accounts_company_calls_post"];
    delete: operations["delete_company_call_accounts_company_calls_delete"];
  };
  "/accounts/sales/meetings": {
    get: operations["get_sales_meetings_accounts_sales_meetings_get"];
    put: operations["update_sales_meeting_accounts_sales_meetings_put"];
    post: operations["create_sales_meeting_accounts_sales_meetings_post"];
    delete: operations["delete_sales_meeting_accounts_sales_meetings_delete"];
  };
  "/accounts/company/meetings": {
    get: operations["get_company_meetings_accounts_company_meetings_get"];
    put: operations["update_company_meeting_accounts_company_meetings_put"];
    post: operations["create_company_meeting_accounts_company_meetings_post"];
    delete: operations["delete_company_meeting_accounts_company_meetings_delete"];
  };
  "/accounts/sales/notes": {
    get: operations["get_sales_notes_accounts_sales_notes_get"];
    put: operations["update_sales_notes_accounts_sales_notes_put"];
    post: operations["create_sales_notes_accounts_sales_notes_post"];
    delete: operations["delete_sales_notes_accounts_sales_notes_delete"];
  };
  "/leads/notes": {
    get: operations["get_lead_notes_leads_notes_get"];
    put: operations["update_lead_notes_leads_notes_put"];
    post: operations["create_lead_notes_leads_notes_post"];
    delete: operations["delete_lead_notes_leads_notes_delete"];
  };
  "/budget_ranges/": {
    get: operations["get_budget_ranges_budget_ranges__get"];
  };
  "/areas/": {
    get: operations["get_areas_areas__get"];
  };
  "/property_types/": {
    get: operations["get_property_types_property_types__get"];
  };
  "/delivery_ranges/": {
    get: operations["get_delivery_ranges_delivery_ranges__get"];
  };
  "/streets/": {
    get: operations["search_streets_streets__get"];
  };
  "/countries/": {
    get: operations["get_countries_countries__get"];
  };
  "/countries/{country_id}": {
    get: operations["get_country_countries__country_id__get"];
  };
  "/countries/{country_id}/states/": {
    get: operations["get_states_countries__country_id__states__get"];
  };
  "/countries/{country_id}/states/{state_id}": {
    get: operations["get_state_countries__country_id__states__state_id__get"];
  };
  "/countries/{country_id}/states/{state_id}/cities/": {
    get: operations["get_cities_countries__country_id__states__state_id__cities__get"];
  };
  "/countries/{country_id}/states/{state_id}/cities/{city_id}": {
    get: operations["get_city_countries__country_id__states__state_id__cities__city_id__get"];
  };
  "/countries/{country_id}/states/{state_id}/cities/{city_id}/districts/": {
    get: operations["get_districts_countries__country_id__states__state_id__cities__city_id__districts__get"];
  };
  "/countries/{country_id}/states/{state_id}/cities/{city_id}/districts/{district_id}": {
    get: operations["get_district_countries__country_id__states__state_id__cities__city_id__districts__district_id__get"];
  };
  "/countries/{country_id}/states/{state_id}/cities/{city_id}/districts/{district_id}/streets/": {
    get: operations["get_streets_countries__country_id__states__state_id__cities__city_id__districts__district_id__streets__get"];
  };
  "/countries/{country_id}/states/{state_id}/cities/{city_id}/districts/{district_id}/streets/{street_id}": {
    get: operations["get_street_countries__country_id__states__state_id__cities__city_id__districts__district_id__streets__street_id__get"];
  };
}

export interface components {
  schemas: {
    /** Actions */
    Actions: {
      /**
       * Calls
       * @default []
       */
      calls?: (Partial<components["schemas"]["SalesAction"]> &
        Partial<components["schemas"]["CompanyAction"]>)[];
      /**
       * Meetings
       * @default []
       */
      meetings?: (Partial<components["schemas"]["SalesAction"]> &
        Partial<components["schemas"]["CompanyAction"]>)[];
    };
    /** Area */
    Area: {
      /** Id */
      id: number;
      /** Area */
      area: string;
    };
    /** Body_login_for_access_token_token_post */
    Body_login_for_access_token_token_post: {
      /** Grant Type */
      grant_type?: string;
      /**
       * Username
       * @default
       */
      username?: string;
      /**
       * Password
       * @default
       */
      password?: string;
      /**
       * Refresh Token
       * @default
       */
      refresh_token?: string;
      /**
       * Scope
       * @default
       */
      scope?: string;
      /** Client Id */
      client_id?: Partial<string> & Partial<unknown>;
      /** Client Secret */
      client_secret?: Partial<string> & Partial<unknown>;
    };
    /**
     * CallStatus
     * @enum {integer}
     */
    CallStatus: 1 | 2;
    /** City */
    City: {
      /** Id */
      id: number;
      /** City */
      city?: Partial<string> & Partial<unknown>;
      state: components["schemas"]["State"];
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** CompanyAccount */
    CompanyAccount: {
      /** Assigned To Id */
      assigned_to_id: number;
      /** Phone */
      phone: string;
      /** Status Id */
      status_id: Partial<number> & Partial<unknown>;
      /**
       * Is Active
       * @default true
       */
      is_active?: boolean;
      /** Added By Id */
      added_by_id: number;
      added_by: components["schemas"]["Employee"];
      lead: components["schemas"]["Lead"];
      Job_title?: Partial<components["schemas"]["JobTitle"]> & Partial<unknown>;
      status: Partial<components["schemas"]["status"]> & Partial<unknown>;
      assigned_to: components["schemas"]["Employee"];
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** CompanyAccountUpdate */
    CompanyAccountUpdate: {
      /** Status Id */
      status_id?: Partial<number> & Partial<unknown>;
      /** Is Active */
      is_active?: Partial<boolean> & Partial<unknown>;
    };
    /** CompanyAction */
    CompanyAction: {
      /** Assigned To Id */
      assigned_to_id: number;
      /** Status Id */
      status_id: Partial<components["schemas"]["CallStatus"]> &
        Partial<components["schemas"]["MeetingStatus"]>;
      /** Company Account Phone */
      company_account_phone: string;
      /** Id */
      id: number;
      assigned_to: components["schemas"]["Employee"];
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
      /**
       * Date
       * Format: date-time
       */
      date: string;
    };
    /** CompanyActionCreate */
    CompanyActionCreate: {
      /** Assigned To Id */
      assigned_to_id: number;
      /** Status Id */
      status_id: Partial<components["schemas"]["CallStatus"]> &
        Partial<components["schemas"]["MeetingStatus"]>;
      /** Company Account Phone */
      company_account_phone: string;
      /**
       * Date
       * @default 2023-11-30T15:08:42.391281
       */
      date?: Partial<string> & Partial<unknown>;
    };
    /** CompanyActionSearch */
    CompanyActionSearch: {
      /** Company Account Phone */
      company_account_phone?: Partial<string> & Partial<unknown>;
      /** Assigned To Id */
      assigned_to_id?: Partial<number> & Partial<unknown>;
      /** Status Id */
      status_id?: Partial<number> & Partial<unknown>;
      /** Date */
      date?: Partial<string> & Partial<unknown>;
    };
    /** CompanyActionUpdate */
    CompanyActionUpdate: {
      /** Status Id */
      status_id?: Partial<number> & Partial<unknown>;
      /** Date */
      date?: Partial<string> & Partial<unknown>;
    };
    /** Country */
    Country: {
      /** Id */
      id: number;
      /** Country */
      country?: Partial<string> & Partial<unknown>;
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** Department */
    Department: {
      /** Id */
      id: number;
      /** Department */
      department: string;
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** District */
    District: {
      /** Id */
      id: number;
      /** District */
      district?: Partial<string> & Partial<unknown>;
      city: components["schemas"]["City"];
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** EducationalDegree */
    EducationalDegree: {
      /** Id */
      id: number;
      /** Degree */
      degree: string;
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** EducationalMajor */
    EducationalMajor: {
      /** Id */
      id: number;
      /** Major */
      major: string;
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** Employee */
    Employee: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      department: components["schemas"]["Department"];
      team: components["schemas"]["Team"];
      position: components["schemas"]["Position"];
      business_email: components["schemas"]["EmployeeEmail"];
      business_phone: components["schemas"]["EmployeePhone"];
      personal_email?: Partial<components["schemas"]["EmployeeEmail"]> &
        Partial<unknown>;
      personal_phone?: Partial<components["schemas"]["EmployeePhone"]> &
        Partial<unknown>;
      termination_info?: Partial<
        components["schemas"]["EmployeeTerminationInfo"]
      > &
        Partial<unknown>;
      educational_qualification: components["schemas"]["EmployeeEducationalQualification"];
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** EmployeeCreate */
    EmployeeCreate: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Gender */
      gender: string;
      /** Department Id */
      department_id: number;
      /** Team Id */
      team_id: number;
      /** Position Id */
      position_id: number;
      /**
       * Date Of Birth
       * Format: date
       */
      date_of_birth: string;
      /**
       * Join Date
       * Format: date
       */
      join_date: string;
      /**
       * Currently Enrolled
       * @default true
       */
      currently_enrolled?: Partial<boolean> & Partial<unknown>;
      /** Business Email */
      business_email: string;
      /** Business Phone */
      business_phone: string;
      /** National Id */
      national_id: string;
      /** Degree Id */
      degree_id: number;
      /** Major Id */
      major_id: number;
      /** Graduation Year */
      graduation_year: number;
    };
    /** EmployeeEducationalQualification */
    EmployeeEducationalQualification: {
      /** Employee Id */
      employee_id: number;
      /** Certificate Id */
      certificate_id: number;
      certificate: components["schemas"]["EducationalDegree"];
      /** Major Id */
      major_id: number;
      major: components["schemas"]["EducationalMajor"];
      /** Graduation Year */
      graduation_year: number;
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** EmployeeEmail */
    EmployeeEmail: {
      /** Employee Id */
      employee_id: number;
      /** Email */
      email: string;
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** EmployeePhone */
    EmployeePhone: {
      /** Employee Id */
      employee_id: number;
      /** Phone */
      phone: string;
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** EmployeeRegister */
    EmployeeRegister: {
      /** Id */
      id: number;
      /** Password */
      password: string;
      /** Personal Email */
      personal_email?: Partial<string> & Partial<unknown>;
      /** Personal Phone */
      personal_phone?: Partial<string> & Partial<unknown>;
    };
    /** EmployeeSearch */
    EmployeeSearch: {
      /** Search */
      search?: Partial<string> & Partial<unknown>;
      /** Ids */
      ids?: Partial<number[]> & Partial<unknown>;
      /** Name */
      name?: Partial<string> & Partial<unknown>;
      /** Gender */
      gender?: Partial<string> & Partial<unknown>;
      /** Department Ids */
      department_ids?: Partial<number[]> & Partial<unknown>;
      /** Team Ids */
      team_ids?: Partial<number[]> & Partial<unknown>;
      /** Position Ids */
      position_ids?: Partial<number[]> & Partial<unknown>;
      /** Date Of Birth */
      date_of_birth?: Partial<string> & Partial<unknown>;
      /** Join Date */
      join_date?: Partial<string> & Partial<unknown>;
      /** Currently Enrolled */
      currently_enrolled?: Partial<boolean> & Partial<unknown>;
      /** Business Email */
      business_email?: Partial<string> & Partial<unknown>;
      /** Business Phone */
      business_phone?: Partial<string> & Partial<unknown>;
      /** National Id */
      national_id?: Partial<string> & Partial<unknown>;
      /** Personal Email */
      personal_email?: Partial<string> & Partial<unknown>;
      /** Personal Phone */
      personal_phone?: Partial<string> & Partial<unknown>;
      /** Major Id */
      major_id?: Partial<number[]> & Partial<unknown>;
      /** Degree Id */
      degree_id?: Partial<number[]> & Partial<unknown>;
      /** Graduation Years */
      graduation_years?: Partial<number[]> & Partial<unknown>;
      /** Resignation Date */
      resignation_date?: Partial<string> & Partial<unknown>;
    };
    /** EmployeeTerminationInfo */
    EmployeeTerminationInfo: {
      /** Employee Id */
      employee_id: number;
      /**
       * Resignation Date
       * Format: date
       */
      resignation_date: string;
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** EmployeeUpdate */
    EmployeeUpdate: {
      /** Search */
      search?: Partial<string> & Partial<unknown>;
      /** Ids */
      ids?: Partial<number[]> & Partial<unknown>;
      /** Name */
      name?: Partial<string> & Partial<unknown>;
      /** Gender */
      gender?: Partial<string> & Partial<unknown>;
      /** Department Ids */
      department_ids?: Partial<number[]> & Partial<unknown>;
      /** Team Ids */
      team_ids?: Partial<number[]> & Partial<unknown>;
      /** Position Ids */
      position_ids?: Partial<number[]> & Partial<unknown>;
      /** Date Of Birth */
      date_of_birth?: Partial<string> & Partial<unknown>;
      /** Join Date */
      join_date?: Partial<string> & Partial<unknown>;
      /** Currently Enrolled */
      currently_enrolled?: Partial<boolean> & Partial<unknown>;
      /** Business Email */
      business_email?: Partial<string> & Partial<unknown>;
      /** Business Phone */
      business_phone?: Partial<string> & Partial<unknown>;
      /** National Id */
      national_id?: Partial<string> & Partial<unknown>;
      /** Personal Email */
      personal_email?: Partial<string> & Partial<unknown>;
      /** Personal Phone */
      personal_phone?: Partial<string> & Partial<unknown>;
      /** Major Id */
      major_id?: Partial<number> & Partial<unknown>;
      /** Degree Id */
      degree_id?: Partial<number> & Partial<unknown>;
      /** Graduation Years */
      graduation_years?: Partial<number[]> & Partial<unknown>;
      /** Resignation Date */
      resignation_date?: Partial<string> & Partial<unknown>;
      /** Department Id */
      department_id?: Partial<number> & Partial<unknown>;
      /** Team Id */
      team_id?: Partial<number> & Partial<unknown>;
      /** Position Id */
      position_id?: Partial<number> & Partial<unknown>;
      /** Graduation Year */
      graduation_year?: Partial<number> & Partial<unknown>;
    };
    /**
     * Gender
     * @enum {string}
     */
    Gender: "male" | "female";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** JobTitle */
    JobTitle: {
      /** Id */
      id: number;
      /** Title */
      title: string;
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** Lead */
    Lead: {
      /** Name */
      name: string;
      /** Phone */
      phone: string;
      /** Assigned To Id */
      assigned_to_id?: Partial<number> & Partial<unknown>;
      /** Email */
      email?: Partial<string> & Partial<unknown>;
      gender?: Partial<components["schemas"]["Gender"]> & Partial<unknown>;
      /** Job Title Id */
      job_title_id?: Partial<number> & Partial<unknown>;
      job_title?: Partial<components["schemas"]["JobTitle"]> & Partial<unknown>;
      /** Added By Id */
      added_by_id: number;
      added_by: components["schemas"]["Employee"];
      assigned_to?: Partial<components["schemas"]["Employee"]> &
        Partial<unknown>;
      status: components["schemas"]["status"];
      /** Interests */
      interests: components["schemas"]["LeadInterest"][];
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** LeadCreate */
    LeadCreate: {
      /** Name */
      name: string;
      /** Phone */
      phone: string;
      /** Assigned To Id */
      assigned_to_id?: Partial<number> & Partial<unknown>;
      /** Email */
      email?: Partial<string> & Partial<unknown>;
      gender?: Partial<components["schemas"]["Gender"]> & Partial<unknown>;
      /** Job Title Id */
      job_title_id?: Partial<number> & Partial<unknown>;
      /** Interests */
      interests: components["schemas"]["LeadInterestCreate"][];
    };
    /** LeadInterest */
    LeadInterest: {
      /** Budget Range Id */
      budget_range_id: number;
      /** Area Range Id */
      area_range_id: number;
      /** Delivery Range Id */
      delivery_range_id: number;
      /** Payment Method Id */
      payment_method_id: number;
      /** Property Type Id */
      property_type_id: number;
      /** Lead Phone */
      lead_phone: string;
      /** Interest Id */
      interest_id: number;
      budget_range?: Partial<components["schemas"]["RangeMoney"]> &
        Partial<unknown>;
      area_range?: Partial<components["schemas"]["RangeInt"]> &
        Partial<unknown>;
      delivery_range?: Partial<components["schemas"]["RangeInt"]> &
        Partial<unknown>;
      payment_method?: Partial<components["schemas"]["PaymentMethod"]> &
        Partial<unknown>;
      property_type?: Partial<components["schemas"]["PropertyType"]> &
        Partial<unknown>;
      /**
       * Areas
       * @default []
       */
      areas?: Partial<components["schemas"]["LeadInterestArea"][]> &
        Partial<unknown>;
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** LeadInterestArea */
    LeadInterestArea: {
      /** Area Id */
      area_id: number;
      area: components["schemas"]["Area"];
    };
    /** LeadInterestCreate */
    LeadInterestCreate: {
      /** Budget Range Id */
      budget_range_id: number;
      /** Area Range Id */
      area_range_id: number;
      /** Delivery Range Id */
      delivery_range_id: number;
      /** Payment Method Id */
      payment_method_id: number;
      /** Property Type Id */
      property_type_id: number;
      /** Areas Ids */
      areas_ids: number[];
    };
    /** LeadNotes */
    LeadNotes: {
      /** Phone */
      phone: string;
      /** Notes */
      notes: string;
      /** Id */
      id: number;
      added_by: components["schemas"]["Employee"];
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** LeadNotesCreate */
    LeadNotesCreate: {
      /** Phone */
      phone: string;
      /** Notes */
      notes: string;
    };
    /** LeadNotesSearch */
    LeadNotesSearch: {
      /** Phone */
      phone?: Partial<string> & Partial<unknown>;
      /** Notes */
      notes?: Partial<string> & Partial<unknown>;
      /** Date Added */
      date_added?: Partial<string> & Partial<unknown>;
      /** Added By Id */
      added_by_id?: Partial<number> & Partial<unknown>;
    };
    /** LeadNotesUpdate */
    LeadNotesUpdate: {
      /** Notes */
      notes: string;
    };
    /** LeadUpdate */
    LeadUpdate: {
      /** Name */
      name?: Partial<string> & Partial<unknown>;
      /** Email */
      email?: Partial<string> & Partial<unknown>;
      gender?: Partial<components["schemas"]["Gender"]> & Partial<unknown>;
      /** Job Title Id */
      job_title_id?: Partial<number> & Partial<unknown>;
      /** Status Id */
      status_id?: Partial<number> & Partial<unknown>;
      /** Interests */
      interests?: Partial<components["schemas"]["LeadInterestCreate"][]> &
        Partial<unknown>;
    };
    /**
     * MeetingStatus
     * @enum {integer}
     */
    MeetingStatus: 1 | 2 | 3 | 4;
    /** PaymentMethod */
    PaymentMethod: {
      /** Id */
      id: number;
      /** Method */
      method: string;
    };
    /** Position */
    Position: {
      /** Id */
      id: number;
      /** Position */
      position: string;
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** PropertyType */
    PropertyType: {
      /** Id */
      id: number;
      /** Type */
      type: string;
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** RangeInt */
    RangeInt: {
      /** Id */
      id: number;
      /** Min */
      min: number;
      /** Max */
      max: number;
    };
    /** RangeMoney */
    RangeMoney: {
      /** Id */
      id: number;
      /** Min */
      min: number;
      /** Max */
      max: number;
    };
    /** SalesAccount */
    SalesAccount: {
      /** Name */
      name: string;
      /** Phone */
      phone: string;
      /** Assigned To Id */
      assigned_to_id?: Partial<number> & Partial<unknown>;
      /** Email */
      email?: Partial<string> & Partial<unknown>;
      gender?: Partial<components["schemas"]["Gender"]> & Partial<unknown>;
      /** Job Title Id */
      job_title_id?: Partial<number> & Partial<unknown>;
      /** Status Id */
      status_id: number;
      /** Added By Id */
      added_by_id: number;
      added_by: components["schemas"]["Employee"];
      job_title?: Partial<components["schemas"]["JobTitle"]> & Partial<unknown>;
      assigned_to: components["schemas"]["Employee"];
      status: components["schemas"]["status"];
      /** Interests */
      interests: components["schemas"]["SalesAccountInterest"][];
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** SalesAccountCreate */
    SalesAccountCreate: {
      /** Name */
      name: string;
      /** Phone */
      phone: string;
      /** Assigned To Id */
      assigned_to_id?: Partial<number> & Partial<unknown>;
      /** Email */
      email?: Partial<string> & Partial<unknown>;
      gender?: Partial<components["schemas"]["Gender"]> & Partial<unknown>;
      /** Job Title Id */
      job_title_id?: Partial<number> & Partial<unknown>;
      /** Status Id */
      status_id: number;
      /** Interests */
      interests: components["schemas"]["SalesAccountInterestCreate"][];
    };
    /** SalesAccountInterest */
    SalesAccountInterest: {
      /** Budget Range Id */
      budget_range_id: number;
      /** Area Range Id */
      area_range_id: number;
      /** Delivery Range Id */
      delivery_range_id: number;
      /** Payment Method Id */
      payment_method_id: number;
      /** Property Type Id */
      property_type_id: number;
      /** Interest Id */
      interest_id: number;
      budget_range?: Partial<components["schemas"]["RangeMoney"]> &
        Partial<unknown>;
      area_range?: Partial<components["schemas"]["RangeInt"]> &
        Partial<unknown>;
      delivery_range?: Partial<components["schemas"]["RangeInt"]> &
        Partial<unknown>;
      payment_method?: Partial<components["schemas"]["PaymentMethod"]> &
        Partial<unknown>;
      property_type?: Partial<components["schemas"]["PropertyType"]> &
        Partial<unknown>;
      /**
       * Areas
       * @default []
       */
      areas?: Partial<components["schemas"]["SalesAccountInterestArea"][]> &
        Partial<unknown>;
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** SalesAccountInterestArea */
    SalesAccountInterestArea: {
      /** Area Id */
      area_id: number;
      area: components["schemas"]["Area"];
    };
    /** SalesAccountInterestCreate */
    SalesAccountInterestCreate: {
      /** Budget Range Id */
      budget_range_id: number;
      /** Area Range Id */
      area_range_id: number;
      /** Delivery Range Id */
      delivery_range_id: number;
      /** Payment Method Id */
      payment_method_id: number;
      /** Property Type Id */
      property_type_id: number;
      /** Areas Ids */
      areas_ids: number[];
    };
    /** SalesAccountSearch */
    SalesAccountSearch: {
      /** Search */
      search?: Partial<string> & Partial<unknown>;
      /** Assigned To Id */
      assigned_to_id?: Partial<number> & Partial<unknown>;
      /** Status Id */
      status_id?: Partial<number> & Partial<unknown>;
      /** Job Title Id */
      job_title_id?: Partial<number> & Partial<unknown>;
      gender?: Partial<components["schemas"]["Gender"]> & Partial<unknown>;
      /** Budget Range Id */
      budget_range_id?: Partial<number> & Partial<unknown>;
      /** Area Range Id */
      area_range_id?: Partial<number> & Partial<unknown>;
      /** Delivery Range Id */
      delivery_range_id?: Partial<number> & Partial<unknown>;
      /** Payment Method Id */
      payment_method_id?: Partial<number> & Partial<unknown>;
      /** Area Id */
      area_id?: Partial<number> & Partial<unknown>;
    };
    /** SalesAccountUpdate */
    SalesAccountUpdate: {
      /** Name */
      name?: Partial<string> & Partial<unknown>;
      /** Email */
      email?: Partial<string> & Partial<unknown>;
      gender?: Partial<components["schemas"]["Gender"]> & Partial<unknown>;
      /** Job Title Id */
      job_title_id?: Partial<number> & Partial<unknown>;
      /** Status Id */
      status_id?: Partial<number> & Partial<unknown>;
      /** Interests */
      interests?: Partial<
        components["schemas"]["SalesAccountInterestCreate"][]
      > &
        Partial<unknown>;
    };
    /** SalesAction */
    SalesAction: {
      /** Assigned To Id */
      assigned_to_id: number;
      /** Status Id */
      status_id: Partial<components["schemas"]["CallStatus"]> &
        Partial<components["schemas"]["MeetingStatus"]>;
      /** Sales Account Phone */
      sales_account_phone: string;
      /** Id */
      id: number;
      sales_account: Partial<components["schemas"]["SalesAccount"]> &
        Partial<unknown>;
      company_account: Partial<components["schemas"]["CompanyAccount"]> &
        Partial<unknown>;
      assigned_to: components["schemas"]["Employee"];
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
      /**
       * Date
       * Format: date-time
       */
      date: string;
    };
    /** SalesActionCreate */
    SalesActionCreate: {
      /** Assigned To Id */
      assigned_to_id: number;
      /** Sales Account Phone */
      sales_account_phone: string;
      /** Status Id */
      status_id: Partial<components["schemas"]["CallStatus"]> &
        Partial<components["schemas"]["MeetingStatus"]>;
      /**
       * Date
       * @default 2023-11-30T15:08:42.385769
       */
      date?: Partial<string> & Partial<unknown>;
    };
    /** SalesActionSearch */
    SalesActionSearch: {
      /** Search */
      search?: Partial<string> & Partial<unknown>;
      /** Sales Account Phone */
      sales_account_phone?: Partial<string> & Partial<unknown>;
      /** Assigned To Id */
      assigned_to_id?: Partial<number> & Partial<unknown>;
      /** Status Id */
      status_id?: Partial<number> & Partial<unknown>;
      /** Date */
      date?: Partial<string> & Partial<unknown>;
      /** Date Added */
      date_added?: Partial<string> & Partial<unknown>;
    };
    /** SalesActionUpdate */
    SalesActionUpdate: {
      /** Status Id */
      status_id?: Partial<number> & Partial<unknown>;
      /** Date */
      date?: Partial<string> & Partial<unknown>;
    };
    /** SalesNotes */
    SalesNotes: {
      /** Assigned To Id */
      assigned_to_id: number;
      /** Phone */
      phone: string;
      /** Notes */
      notes: string;
      /** Id */
      id: number;
      assigned_to: components["schemas"]["Employee"];
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** SalesNotesCreate */
    SalesNotesCreate: {
      /** Assigned To Id */
      assigned_to_id: number;
      /** Phone */
      phone: string;
      /** Notes */
      notes: string;
    };
    /** SalesNotesSearch */
    SalesNotesSearch: {
      /** Phone */
      phone?: Partial<string> & Partial<unknown>;
      /** Assigned To Id */
      assigned_to_id?: Partial<number> & Partial<unknown>;
      /** Notes */
      notes?: Partial<string> & Partial<unknown>;
      /** Date Added */
      date_added?: Partial<string> & Partial<unknown>;
    };
    /** SalesNotesUpdate */
    SalesNotesUpdate: {
      /** Notes */
      notes: string;
    };
    /** State */
    State: {
      /** Id */
      id: number;
      /** State */
      state?: Partial<string> & Partial<unknown>;
      country: components["schemas"]["Country"];
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** Street */
    Street: {
      /** Id */
      id: number;
      /** Street */
      street?: Partial<string> & Partial<unknown>;
      district: components["schemas"]["District"];
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** Team */
    Team: {
      /** Id */
      id: number;
      /** Team */
      team: string;
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
    /** Token */
    Token: {
      /** Access Token */
      access_token: string;
      /** Token Type */
      token_type: string;
      /** Expires In */
      expires_in: number;
      /** Refresh Token */
      refresh_token: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (Partial<string> & Partial<number>)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** status */
    status: {
      /** Id */
      id: number;
      /** Status */
      status: string;
      /**
       * Date Added
       * Format: date-time
       */
      date_added: string;
    };
  };
}

export interface operations {
  login_for_access_token_token_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_for_access_token_token_post"];
      };
    };
  };
  /**
   * Retrieve a list of employees based on the provided search criteria. If no search criteria is provided, return all employees.
   *
   * Permissions:
   * - Admins and owners can view all employees.
   * - Team leaders can only view their own team members.
   * - Other employees can only view themselves.
   */
  get_employees_employees__get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Employee"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": Partial<components["schemas"]["EmployeeSearch"]> &
          Partial<unknown>;
      };
    };
  };
  /** Create a new employee. */
  create_employee_employees__post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Employee"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmployeeCreate"];
      };
    };
  };
  /**
   * Retrieve information about a specific employee by `id`.
   *
   * Permissions:
   * - Admins and owners can view all employees.
   * - Team leaders can only view their own team members.
   * - Other employees can only view themselves.
   */
  get_employee_employees__employee_id__get: {
    parameters: {
      path: {
        employee_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Employee"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update information about a specific employee by `id`.
   *
   * Permissions:
   * - Admins and owners can update all employees.
   */
  update_employee_employees__employee_id__put: {
    parameters: {
      path: {
        employee_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Employee"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmployeeUpdate"];
      };
    };
  };
  /** Delete a specific employee by `id`. */
  delete_employee_employees__employee_id__delete: {
    parameters: {
      path: {
        employee_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Retrieve information about a specific employee by `bussines_email`.
   *
   * Permissions:
   * - Admins and owners can view all employees.
   * - Team leaders can only view their own team members.
   * - Other employees can only view themselves.
   */
  get_employee_by_email_employees_email__email__get: {
    parameters: {
      path: {
        email: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Employee"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Register a new employee.
   *
   * Permissions:
   * - Only unregistered employees can register.
   */
  register_employee_employees_register_put: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Employee"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmployeeRegister"];
      };
    };
  };
  get_sales_accounts_accounts_sales_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SalesAccount"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": Partial<
          components["schemas"]["SalesAccountSearch"]
        > &
          Partial<unknown>;
      };
    };
  };
  update_sales_account_accounts_sales_put: {
    parameters: {
      query: {
        added_by: number;
        phone: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SalesAccount"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SalesAccountUpdate"];
      };
    };
  };
  create_sales_account_accounts_sales_post: {
    parameters: {
      query: {
        assigned_to?: Partial<number> & Partial<unknown>;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SalesAccount"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SalesAccountCreate"];
      };
    };
  };
  delete_sales_account_accounts_sales_delete: {
    parameters: {
      query: {
        added_by: number;
        phone: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  rotate_lead_leads_rotate_post: {
    parameters: {
      query: {
        lead_phone: string;
        to?: Partial<number> & Partial<unknown>;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": Partial<components["schemas"]["CompanyAccount"]> &
            Partial<unknown>;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_leads_leads__get: {
    parameters: {
      query: {
        search?: Partial<string> & Partial<unknown>;
        assigned_to_id?: Partial<number> & Partial<unknown>;
        status_id?: Partial<number> & Partial<unknown>;
        job_title_id?: Partial<number> & Partial<unknown>;
        gender?: Partial<components["schemas"]["Gender"]> & Partial<unknown>;
        budget_range_id?: Partial<number> & Partial<unknown>;
        area_range_id?: Partial<number> & Partial<unknown>;
        delivery_range_id?: Partial<number> & Partial<unknown>;
        payment_method_id?: Partial<number> & Partial<unknown>;
        area_id?: Partial<number> & Partial<unknown>;
        property_type_id?: Partial<number> & Partial<unknown>;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Lead"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_lead_leads__put: {
    parameters: {
      query: {
        phone: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Lead"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LeadUpdate"];
      };
    };
  };
  create_lead_leads__post: {
    parameters: {
      query: {
        assigned_to?: Partial<number> & Partial<unknown>;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Lead"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LeadCreate"];
      };
    };
  };
  delete_lead_leads__delete: {
    parameters: {
      query: {
        phone: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_company_accounts_accounts_company_get: {
    parameters: {
      query: {
        status_id?: Partial<number> & Partial<unknown>;
        is_active?: Partial<boolean> & Partial<unknown>;
        search?: Partial<string> & Partial<unknown>;
        assigned_to_id?: Partial<number> & Partial<unknown>;
        lead_status_id?: Partial<number> & Partial<unknown>;
        job_title_id?: Partial<number> & Partial<unknown>;
        gender?: Partial<components["schemas"]["Gender"]> & Partial<unknown>;
        budget_range_id?: Partial<number> & Partial<unknown>;
        area_range_id?: Partial<number> & Partial<unknown>;
        delivery_range_id?: Partial<number> & Partial<unknown>;
        payment_method_id?: Partial<number> & Partial<unknown>;
        area_id?: Partial<number> & Partial<unknown>;
        property_type_id?: Partial<number> & Partial<unknown>;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CompanyAccount"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_company_account_accounts_company_put: {
    parameters: {
      query: {
        assigned_to_id: number;
        phone: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CompanyAccount"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompanyAccountUpdate"];
      };
    };
  };
  delete_company_account_accounts_company_delete: {
    parameters: {
      query: {
        assigned_to: number;
        phone: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_teams_teams__get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Team"][];
        };
      };
    };
  };
  get_actions_actions__get: {
    parameters: {
      query: {
        search?: Partial<string> & Partial<unknown>;
        day?: Partial<string> & Partial<unknown>;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Actions"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_sales_calls_accounts_sales_calls_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SalesAction"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": Partial<
          components["schemas"]["SalesActionSearch"]
        > &
          Partial<unknown>;
      };
    };
  };
  update_sales_call_accounts_sales_calls_put: {
    parameters: {
      query: {
        id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SalesAction"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SalesActionUpdate"];
      };
    };
  };
  create_sales_call_accounts_sales_calls_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SalesAction"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SalesActionCreate"];
      };
    };
  };
  delete_sales_call_accounts_sales_calls_delete: {
    parameters: {
      query: {
        id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_company_calls_accounts_company_calls_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CompanyAction"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": Partial<
          components["schemas"]["CompanyActionSearch"]
        > &
          Partial<unknown>;
      };
    };
  };
  update_company_call_accounts_company_calls_put: {
    parameters: {
      query: {
        id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CompanyAction"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompanyActionUpdate"];
      };
    };
  };
  create_company_call_accounts_company_calls_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CompanyAction"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompanyActionCreate"];
      };
    };
  };
  delete_company_call_accounts_company_calls_delete: {
    parameters: {
      query: {
        id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_sales_meetings_accounts_sales_meetings_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SalesAction"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": Partial<
          components["schemas"]["SalesActionSearch"]
        > &
          Partial<unknown>;
      };
    };
  };
  update_sales_meeting_accounts_sales_meetings_put: {
    parameters: {
      query: {
        id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SalesAction"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SalesActionUpdate"];
      };
    };
  };
  create_sales_meeting_accounts_sales_meetings_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SalesAction"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SalesActionCreate"];
      };
    };
  };
  delete_sales_meeting_accounts_sales_meetings_delete: {
    parameters: {
      query: {
        id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_company_meetings_accounts_company_meetings_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CompanyAction"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": Partial<
          components["schemas"]["CompanyActionSearch"]
        > &
          Partial<unknown>;
      };
    };
  };
  update_company_meeting_accounts_company_meetings_put: {
    parameters: {
      query: {
        id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CompanyAction"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompanyActionUpdate"];
      };
    };
  };
  create_company_meeting_accounts_company_meetings_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CompanyAction"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompanyActionCreate"];
      };
    };
  };
  delete_company_meeting_accounts_company_meetings_delete: {
    parameters: {
      query: {
        id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_sales_notes_accounts_sales_notes_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SalesNotes"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": Partial<components["schemas"]["SalesNotesSearch"]> &
          Partial<unknown>;
      };
    };
  };
  update_sales_notes_accounts_sales_notes_put: {
    parameters: {
      query: {
        id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SalesNotes"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SalesNotesUpdate"];
      };
    };
  };
  create_sales_notes_accounts_sales_notes_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SalesNotes"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SalesNotesCreate"];
      };
    };
  };
  delete_sales_notes_accounts_sales_notes_delete: {
    parameters: {
      query: {
        id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_lead_notes_leads_notes_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LeadNotes"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": Partial<components["schemas"]["LeadNotesSearch"]> &
          Partial<unknown>;
      };
    };
  };
  update_lead_notes_leads_notes_put: {
    parameters: {
      query: {
        id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LeadNotes"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LeadNotesUpdate"];
      };
    };
  };
  create_lead_notes_leads_notes_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LeadNotes"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LeadNotesCreate"];
      };
    };
  };
  delete_lead_notes_leads_notes_delete: {
    parameters: {
      query: {
        id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_budget_ranges_budget_ranges__get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RangeMoney"][];
        };
      };
    };
  };
  get_areas_areas__get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Area"][];
        };
      };
    };
  };
  get_property_types_property_types__get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PropertyType"][];
        };
      };
    };
  };
  get_delivery_ranges_delivery_ranges__get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RangeInt"][];
        };
      };
    };
  };
  search_streets_streets__get: {
    parameters: {
      query: {
        country?: Partial<string> & Partial<unknown>;
        state?: Partial<string> & Partial<unknown>;
        city?: Partial<string> & Partial<unknown>;
        district?: Partial<string> & Partial<unknown>;
        street?: Partial<string> & Partial<unknown>;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Street"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_countries_countries__get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Country"][];
        };
      };
    };
  };
  get_country_countries__country_id__get: {
    parameters: {
      path: {
        country_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Country"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_states_countries__country_id__states__get: {
    parameters: {
      path: {
        country_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["State"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_state_countries__country_id__states__state_id__get: {
    parameters: {
      path: {
        country_id: number;
        state_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["State"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_cities_countries__country_id__states__state_id__cities__get: {
    parameters: {
      path: {
        country_id: number;
        state_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["City"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_city_countries__country_id__states__state_id__cities__city_id__get: {
    parameters: {
      path: {
        country_id: number;
        state_id: number;
        city_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["City"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_districts_countries__country_id__states__state_id__cities__city_id__districts__get: {
    parameters: {
      path: {
        country_id: number;
        state_id: number;
        city_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["District"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_district_countries__country_id__states__state_id__cities__city_id__districts__district_id__get: {
    parameters: {
      path: {
        country_id: number;
        state_id: number;
        city_id: number;
        district_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["District"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_streets_countries__country_id__states__state_id__cities__city_id__districts__district_id__streets__get: {
    parameters: {
      path: {
        country_id: number;
        state_id: number;
        city_id: number;
        district_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Street"][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_street_countries__country_id__states__state_id__cities__city_id__districts__district_id__streets__street_id__get: {
    parameters: {
      path: {
        country_id: number;
        state_id: number;
        city_id: number;
        district_id: number;
        street_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Street"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}

export interface external {}
